version: '3.7'
services:
  koki-pay:
    build: .
    ports:
      - "8010:8010"
    environment:
      - DATABASE_URL=postgres://koki_user:koki_pass@koki-pay-db:5432/koki_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - koki-pay-db
      - redis
    networks:
      - koki-pay-network

  koki-pay-db:
    container_name: koki-pay-db
    image: postgres:13
    environment:
      - POSTGRES_DB=koki_db
      - POSTGRES_USER=koki_user
      - POSTGRES_PASSWORD=koki_pass
    volumes:
      - koki_postgres_data:/var/lib/postgresql/data
    networks:
      - koki-pay-network

  redis:
    image: redis:6
    networks:
      - koki-pay-network

  koki-pay-celery:
    build: .
    command: /usr/local/bin/celery -A silver worker --loglevel=info
    environment:
      - DATABASE_URL=postgres://koki_user:koki_pass@koki-pay-db:5432/koki_db
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - koki-pay-db
      - redis
    networks:
      - koki-pay-network

volumes:
  koki_postgres_data:

networks:
  koki-pay-network:
    driver: bridge
